// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace DancingGoat.Models
{
    public partial class CallToAction
    {
        public const string Codename = "call_to_action";
        public const string ImageCodename = "image";
        public const string TitleCodename = "title";
        public const string TextCodename = "text";
        public const string ShortTextCodename = "short_text";
        public const string ActionButtonTextCodename = "action_button_text";
        public const string PersonaCodename = "persona";
        public const string DeliveryChannelCodename = "delivery_channel";
        public const string InternalContentLinkCodename = "internal_content_link";
        public const string ExternalLinkCodename = "external_link";
        public const string CustomActivityNameCodename = "custom_activity_name";

        public IEnumerable<Asset> Image { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string ShortText { get; set; }
        public string ActionButtonText { get; set; }
        public IEnumerable<TaxonomyTerm> Persona { get; set; }
        public IEnumerable<TaxonomyTerm> DeliveryChannel { get; set; }
        public IEnumerable<object> InternalContentLink { get; set; }
        public string ExternalLink { get; set; }
        public string CustomActivityName { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}