// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace DancingGoat.Models
{
    public partial class NavigationItem
    {
        public const string Codename = "navigation_item";
        public const string NameCodename = "name";
        public const string UrlSegmentCodename = "url_segment";

        public string Name { get; set; }
        public string UrlSegment { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}