// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace DancingGoat.Models
{
    public partial class SelectedCafes
    {
        public const string Codename = "selected_cafes";
        public const string CallToActionsCodename = "call_to_actions";
        public const string HandpickedCafesCodename = "handpicked_cafes";

        public IEnumerable<object> CallToActions { get; set; }
        public IEnumerable<object> HandpickedCafes { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}